pipeline {
  agent any

  environment {
    FLASK_PORT = '5000'
  }

  stages {
    stage('Clone') {
      steps {
        git credentialsId: '4e2a7258-ae6a-4d20-9909-8158a49722c0', url: 'https://github.com/mr2Ashish/ci-cd-deployment.git'
      }
    }

    stage('Install Python Dependencies') {
      steps {
        sh 'pip3 install -r backend/requirements.txt'
      }
    }

    stage('Run Tests') {
      steps {
        echo 'No tests yet — add pytest later!'
      }
    }

    stage('Restart Flask') {
      steps {
        sh 'pm2 restart app.py || pm2 start backend/app.py --interpreter python3'
      }
    }
  }
}
